/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Carrinho.Estoque;
import alcoolicas.Cerveja;
import alcoolicas.Licor;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import semAlcool.Refrigerante;
import semAlcool.Suco;

/**
 *
 * @author Gabriel
 */
public class CadProduto extends javax.swing.JFrame  {
    private ControleEstoque parent;
     private JFrame out; 
    /**
     * Creates new form CadProduto
     */
     
     
     private Estoque estoque;
    public CadProduto() {
        parent = new ControleEstoque();
        initComponents();
        lpSemAlcool.setVisible(false);
        out = new JFrame();
    }
    
    public void setEstoque(Estoque e){
        this.estoque = e;
    }
    
    public CadProduto(Estoque e) {
        parent = new ControleEstoque();
        initComponents();
        lpSemAlcool.setVisible(false);
        out = new JFrame();
        this.estoque = e;
    }

    public void setParent(ControleEstoque e){
        parent = e;
    }
    
    private void showAddInfo(Component cp){
        out.add(cp);
        out.setSize(this.getWidth() - 50, 200);
        out.setVisible(true);                     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bebidas = new javax.swing.ButtonGroup();
        lpCerveja = new javax.swing.JLayeredPane();
        panelExterno = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ckArtesanal = new javax.swing.JCheckBox();
        tfTipo = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lpLicor = new javax.swing.JLayeredPane();
        panelExterno1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfLicSabor = new javax.swing.JTextField();
        btnOK1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfPais = new javax.swing.JTextField();
        lpSuco = new javax.swing.JLayeredPane();
        panelExterno2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnOK2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        ckNatural = new javax.swing.JCheckBox();
        ckAcucar = new javax.swing.JCheckBox();
        lpRefrigerante = new javax.swing.JLayeredPane();
        panelExterno4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnOK4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        ckCafeina = new javax.swing.JCheckBox();
        ckDiet = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sAlcool = new javax.swing.JRadioButton();
        cAlcool = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        lpAlcoolica = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        tfTeor = new javax.swing.JTextField();
        comboBebidasA = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lpSemAlcool = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        tfSabor = new javax.swing.JTextField();
        comboBebidasS = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        btnCancell = new javax.swing.JButton();

        lpCerveja.setBackground(java.awt.Color.gray);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Qual é o tipo da cerveja?");

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cerveja");

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("É artesanal?");

        ckArtesanal.setText("Artesanal");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExternoLayout = new javax.swing.GroupLayout(panelExterno);
        panelExterno.setLayout(panelExternoLayout);
        panelExternoLayout.setHorizontalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExternoLayout.createSequentialGroup()
                .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExternoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(panelExternoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(98, 98, 98)))
                        .addGap(18, 18, 18)
                        .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckArtesanal)
                            .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelExternoLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelExternoLayout.setVerticalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExternoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ckArtesanal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        lpCerveja.setLayer(panelExterno, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpCervejaLayout = new javax.swing.GroupLayout(lpCerveja);
        lpCerveja.setLayout(lpCervejaLayout);
        lpCervejaLayout.setHorizontalGroup(
            lpCervejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lpCervejaLayout.setVerticalGroup(
            lpCervejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpCervejaLayout.createSequentialGroup()
                .addComponent(panelExterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lpLicor.setBackground(java.awt.Color.gray);

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sabor do licor:");

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LICOR");

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("País de origem:");

        javax.swing.GroupLayout panelExterno1Layout = new javax.swing.GroupLayout(panelExterno1);
        panelExterno1.setLayout(panelExterno1Layout);
        panelExterno1Layout.setHorizontalGroup(
            panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno1Layout.createSequentialGroup()
                .addGroup(panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExterno1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)))
                    .addGroup(panelExterno1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLicSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelExterno1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnOK1)))
                .addGap(18, 18, Short.MAX_VALUE))
        );
        panelExterno1Layout.setVerticalGroup(
            panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfLicSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExterno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lpLicor.setLayer(panelExterno1, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpLicorLayout = new javax.swing.GroupLayout(lpLicor);
        lpLicor.setLayout(lpLicorLayout);
        lpLicorLayout.setHorizontalGroup(
            lpLicorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lpLicorLayout.setVerticalGroup(
            lpLicorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpLicorLayout.createSequentialGroup()
                .addComponent(panelExterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lpSuco.setBackground(java.awt.Color.gray);

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("O SUCO É NATUAL?");

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SUCO");

        btnOK2.setText("OK");
        btnOK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TEM AÇUCAR?");

        ckNatural.setText("NATURAL");

        ckAcucar.setText("AÇUCAR");
        ckAcucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAcucarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExterno2Layout = new javax.swing.GroupLayout(panelExterno2);
        panelExterno2.setLayout(panelExterno2Layout);
        panelExterno2Layout.setHorizontalGroup(
            panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno2Layout.createSequentialGroup()
                .addGroup(panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExterno2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckAcucar)
                            .addComponent(ckNatural)))
                    .addGroup(panelExterno2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnOK2)))
                .addGap(61, 61, 61))
        );
        panelExterno2Layout.setVerticalGroup(
            panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addGap(21, 21, 21)
                .addGroup(panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ckNatural))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExterno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ckAcucar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lpSuco.setLayer(panelExterno2, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpSucoLayout = new javax.swing.GroupLayout(lpSuco);
        lpSuco.setLayout(lpSucoLayout);
        lpSucoLayout.setHorizontalGroup(
            lpSucoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lpSucoLayout.setVerticalGroup(
            lpSucoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSucoLayout.createSequentialGroup()
                .addComponent(panelExterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lpRefrigerante.setBackground(java.awt.Color.gray);

        jLabel23.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CONTÉM CAFEÍNA");

        jLabel24.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("REFRIGERANTE");

        btnOK4.setText("OK");
        btnOK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK4ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 204, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("É DIET");

        ckCafeina.setText("CAFEÍNA");

        ckDiet.setText("DIET");
        ckDiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExterno4Layout = new javax.swing.GroupLayout(panelExterno4);
        panelExterno4.setLayout(panelExterno4Layout);
        panelExterno4Layout.setHorizontalGroup(
            panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno4Layout.createSequentialGroup()
                .addGroup(panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExterno4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckDiet)
                            .addComponent(ckCafeina)))
                    .addGroup(panelExterno4Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnOK4)))
                .addGap(61, 61, 61))
        );
        panelExterno4Layout.setVerticalGroup(
            panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExterno4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addGap(21, 21, 21)
                .addGroup(panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ckCafeina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExterno4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ckDiet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lpRefrigerante.setLayer(panelExterno4, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout lpRefrigeranteLayout = new javax.swing.GroupLayout(lpRefrigerante);
        lpRefrigerante.setLayout(lpRefrigeranteLayout);
        lpRefrigeranteLayout.setHorizontalGroup(
            lpRefrigeranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lpRefrigeranteLayout.setVerticalGroup(
            lpRefrigeranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpRefrigeranteLayout.createSequentialGroup()
                .addComponent(panelExterno4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTOQUE DE PRODUTOS - CADASTRO");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bar Virtual");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        bebidas.add(sAlcool);
        sAlcool.setForeground(new java.awt.Color(255, 255, 255));
        sAlcool.setText("Sem Álcool");
        sAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAlcoolActionPerformed(evt);
            }
        });

        bebidas.add(cAlcool);
        cAlcool.setForeground(new java.awt.Color(255, 255, 255));
        cAlcool.setSelected(true);
        cAlcool.setText("Alcoólica");
        cAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAlcoolActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de bebida:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setLabelFor(tfNome);
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setLabelFor(tfNome);
        jLabel5.setText("Valor:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setLabelFor(tfNome);
        jLabel6.setText("Quantidade:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64)
                                .addComponent(cAlcool)
                                .addGap(36, 36, 36)
                                .addComponent(sAlcool))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sAlcool)
                    .addComponent(cAlcool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lpAlcoolica.setBackground(new java.awt.Color(0, 102, 0));
        lpAlcoolica.setForeground(new java.awt.Color(0, 102, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setLabelFor(tfNome);
        jLabel7.setText("TEOR");

        comboBebidasA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cerveja", "Licor" }));
        comboBebidasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBebidasAActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setLabelFor(tfNome);
        jLabel8.setText("BEBIDA:");

        lpAlcoolica.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpAlcoolica.setLayer(tfTeor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpAlcoolica.setLayer(comboBebidasA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpAlcoolica.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpAlcoolicaLayout = new javax.swing.GroupLayout(lpAlcoolica);
        lpAlcoolica.setLayout(lpAlcoolicaLayout);
        lpAlcoolicaLayout.setHorizontalGroup(
            lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpAlcoolicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTeor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBebidasA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lpAlcoolicaLayout.setVerticalGroup(
            lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpAlcoolicaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTeor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lpAlcoolicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBebidasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3))
        );

        lpSemAlcool.setBackground(new java.awt.Color(0, 102, 0));
        lpSemAlcool.setForeground(new java.awt.Color(0, 102, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setLabelFor(tfNome);
        jLabel9.setText("SABOR:");

        comboBebidasS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refrigerante", "Suco" }));
        comboBebidasS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBebidasSActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setLabelFor(tfNome);
        jLabel10.setText("BEBDIDA:");

        lpSemAlcool.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSemAlcool.setLayer(tfSabor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSemAlcool.setLayer(comboBebidasS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSemAlcool.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpSemAlcoolLayout = new javax.swing.GroupLayout(lpSemAlcool);
        lpSemAlcool.setLayout(lpSemAlcoolLayout);
        lpSemAlcoolLayout.setHorizontalGroup(
            lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSemAlcoolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBebidasS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lpSemAlcoolLayout.setVerticalGroup(
            lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSemAlcoolLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lpSemAlcoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBebidasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(3, 3, 3))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true));

        btnCadastro.setBackground(new java.awt.Color(0, 204, 0));
        btnCadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastro.setText("CADASTRAR");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnCancell.setBackground(new java.awt.Color(0, 204, 0));
        btnCancell.setForeground(new java.awt.Color(0, 0, 0));
        btnCancell.setText("CANCELAR");
        btnCancell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancell, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lpSemAlcool)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lpAlcoolica)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lpAlcoolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lpSemAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBebidasSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBebidasSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBebidasSActionPerformed

    private void comboBebidasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBebidasAActionPerformed
    }//GEN-LAST:event_comboBebidasAActionPerformed

    private void cAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAlcoolActionPerformed
        lpAlcoolica.setVisible(true);
        lpSemAlcool.setVisible(false);
    }//GEN-LAST:event_cAlcoolActionPerformed

    private void sAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAlcoolActionPerformed
        lpSemAlcool.setVisible(true);
        lpAlcoolica.setVisible(false);
    }//GEN-LAST:event_sAlcoolActionPerformed

    private void btnCancellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancellActionPerformed
//pegando os dados comuns
        private String nome, bebida, sabor;
        private double valor, teor;
        private int quantidade;

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed

        
        nome = tfNome.getText();
        valor = Double.parseDouble(tfValor.getText());
        quantidade = Integer.parseInt(tfQuantidade.getText());
        
        if(bebidas.isSelected(cAlcool.getModel())){//se for bebida alcoolica     
            teor = Double.parseDouble(tfTeor.getText());
            bebida = (String) comboBebidasA.getSelectedItem();
            switch(bebida){
                case "Cerveja":
                    System.out.println("Cerveja");
                    showAddInfo(lpCerveja);
                    break;
                case "Licor":
                    System.out.println("Licor");
                    showAddInfo(lpLicor);
                    break;
            }
        }else{//se for sem alcool
            sabor = tfSabor.getText();
            bebida = (String) comboBebidasS.getSelectedItem();
            switch(bebida){
                case "Refrigerante":
                    System.out.println("Refrigerante");
                    showAddInfo(lpRefrigerante);
                    break;
                case "Suco":
                    System.out.println("Suco");
                    showAddInfo(lpSuco);
                    break;   
            }
        }
       

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        out.setVisible(false);
        String tipo = tfTipo.getText();
        boolean artesanal = ckArtesanal.isSelected();
        
        Cerveja cerv = new Cerveja(tipo, artesanal, teor, 1, nome, valor, quantidade);
        
        estoque.adicionarProduto(cerv);

        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        out.setVisible(false);
        String saborL = tfLicSabor.getText();
        String origem = tfPais.getText();
        Licor lic = new Licor(saborL, origem, teor, 2, nome, valor, quantidade);
     
        estoque.adicionarProduto(lic);

        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void btnOK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK2ActionPerformed
        out.setVisible(false);
        boolean natural = ckNatural.isSelected();
        boolean acucar = ckAcucar.isSelected();
        Suco suco = new Suco(natural, acucar, sabor, 4, nome, valor, quantidade);
        
        estoque.adicionarProduto(suco);

        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOK2ActionPerformed

    private void ckAcucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAcucarActionPerformed
   
    }//GEN-LAST:event_ckAcucarActionPerformed

    private void btnOK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK4ActionPerformed
        out.setVisible(false);
        boolean diet = ckDiet.isSelected();
        boolean cafeina = ckCafeina.isSelected();
        Refrigerante refri = new Refrigerante(cafeina, diet, sabor, 5, nome, valor, quantidade);
         
        estoque.adicionarProduto(refri);

        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOK4ActionPerformed

    private void ckDietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProduto().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bebidas;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancell;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnOK2;
    private javax.swing.JButton btnOK4;
    private javax.swing.JRadioButton cAlcool;
    private javax.swing.JCheckBox ckAcucar;
    private javax.swing.JCheckBox ckArtesanal;
    private javax.swing.JCheckBox ckCafeina;
    private javax.swing.JCheckBox ckDiet;
    private javax.swing.JCheckBox ckNatural;
    private javax.swing.JComboBox<String> comboBebidasA;
    private javax.swing.JComboBox<String> comboBebidasS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLayeredPane lpAlcoolica;
    private javax.swing.JLayeredPane lpCerveja;
    private javax.swing.JLayeredPane lpLicor;
    private javax.swing.JLayeredPane lpRefrigerante;
    private javax.swing.JLayeredPane lpSemAlcool;
    private javax.swing.JLayeredPane lpSuco;
    private javax.swing.JPanel panelExterno;
    private javax.swing.JPanel panelExterno1;
    private javax.swing.JPanel panelExterno2;
    private javax.swing.JPanel panelExterno4;
    private javax.swing.JRadioButton sAlcool;
    private javax.swing.JTextField tfLicSabor;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfSabor;
    private javax.swing.JTextField tfTeor;
    private javax.swing.JTextField tfTipo;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

}
